### PR TITLE
counting command for checking highscore and current

### PR DESCRIPTION
**Pull request by emilianya**

### CODE REVIEW

**Comment by nyakase** [comment]
fuck

**Review by nyakase — CHANGES_REQUESTED** [review]
there's a lot of eslint errors, please fix them

**Comment by emilianya** [comment]
This isnt the most beatiful command but it does its job, I'm hosting it on another bot until we get it on vukkybot

**Comment by ProFireDev** [comment]
:spaghetti: :spaghetti:

**Review by nyakase — APPROVED** [review]

**Pull request merged**
